1. What does Pandas stand for?

    References both “Panel Data” and “Python Data Analysis”

2. What are the 2 collections used in Pandas?

    DataFrame and Series

3. Name 4 things Pandas can do for us.

    load
    manipulate
    prepare
    model

4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?

    inplace

5. What is a CSV?

    Comma Seperated Files which contain plain text and is a well know format that can be read by everyone including Pandas.

6. When cleaning data what values do we not like in our data?

    Null values

In [13]:
#7 Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarray = array.reshape(2, 3, 2)

print(newarray)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [14]:
#8 Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

import numpy as np
array = np.linspace(0, 20, num=6)
print(array)


[ 0.  4.  8. 12. 16. 20.]


In [17]:
#9 Make a Deep Copy of the above array
import numpy as np
import copy

array = np.linspace(0, 20)
print(array)
copied_array = copy.deepcopy(array)
print(copied_array)


[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]
[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13

In [30]:
#11 Concatenate these 3 arrays into a new array named 'newArray'...

array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])
newArray= np.concatenate((array1,array2,array3))
print(newArray)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [35]:
#12 Sort 'newArray' in order into 'sortedArray'
newArray= np.concatenate((array1,array2,array3))
sortedArray=np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [39]:
#13 Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

reshapedArray = sortedArray.reshape(2, 2, 3)
print(reshapedArray)

[[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]


In [43]:
#14 Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

first, second, = reshapedArray
first1, first2 = first
second1, second2 =second
print(first1)
print(first2)
print(second1)
print(second2)


[16 25  2]
[11  4 13]
[ 7 81  5]
[ 6 11 12]


In [11]:
#15 Combined and sort the following arrays into one called 'comboArray' ...

import numpy as np

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

conArray= np.concatenate((one,two,three))
comboArray= np.sort(conArray)
print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [12]:
#16 Take 'comboArray' and perform the following slicing activities:

sec1 = comboArray[1]
print(sec1)

sec2 = comboArray[2:]
print(sec2)

sec3 = comboArray[3:15]
print(sec3)

sec4 = comboArray[-6:]
print(sec4)

sec5 = comboArray[0:-10]
print(sec5)

sec6 = comboArray[16::2]
print(sec6)

sec7 = comboArray[::-5]
print(sec7)

1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [58]:
#20 Using Series, create a DataFrame that looks like this:

import pandas as pd

ingredients = pd.Series(['flour', 'milk', 'eggs', 'spam'], name = 'Ingredients')
quantity = pd.Series([4,1,2,1], name = 'Quanitity')
unit = pd.Series(['cups', 'cup', 'large', 'can'], name = 'Unit')

Dinner = pd.concat([ingredients, quantity, unit], axis = 1)
print(Dinner)


  Ingredients  Quanitity   Unit
0       flour          4   cups
1        milk          1    cup
2        eggs          2  large
3        spam          1    can


In [61]:
#21 Take this data and create a DataFrame named studentData

import pandas as pd

studentData = pd.DataFrame ({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }
)

print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [64]:
#22 Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

studentData.insert(7, 'deserts', ['ice cream', 'cashew fudge', 'waffles', 'carrot halwa'], True )
print(studentData)


      Name  Height Qualification  address  Age        Pets           sport   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts  \
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        deserts       deserts  
0     ice cream     ice cream  
1  cashew fudge  cashew fudge  
2       waffles       waffles  
3  carrot halwa  carrot halwa  


In [65]:
#23 Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by = ['Name', 'address'], inplace = True)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket  \
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        deserts       deserts  
3  carrot halwa  carrot halwa  
2       waffles       waffles  
0     ice cream     ice cream  
1  cashew fudge  cashew fudge  


In [66]:
#24 Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')

In [2]:
#25 (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 

import pandas as pd
vegetables = pd.DataFrame(['Peppers', 'Corn', 'Broccoli', 'Eggplant'], 
                          ['Red', 'Yellow', 'Green', 'Purple'])

flavor = pd.Series(['Spicy', 'Sweet', 'Bland', 'Bland'])

vegetables.loc[:, ['Flavor']] = ['Spicy', 'Sweet', 'Bland', 'Bland']

print(vegetables)

vegetables.to_csv('vegetables')


               0 Flavor
Red      Peppers  Spicy
Yellow      Corn  Sweet
Green   Broccoli  Bland
Purple  Eggplant  Bland


In [16]:
#25 (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

import pandas as pd

veggies=pd.read_csv('vegetables')
print(veggies)
veggies = pd.DataFrame(['Peppers', 'Corn', 'Broccoli', 'Eggplant'], 
                          ['Red', 'Yellow', 'Green', 'Purple'])
veggies= veggies.replace(to_replace='Bland',value="gross")
print(veggies)

veggies.to_csv('veggies')

  Unnamed: 0         0 Flavor
0        Red   Peppers  Spicy
1     Yellow      Corn  Sweet
2      Green  Broccoli  Bland
3     Purple  Eggplant  Bland
               0
Red      Peppers
Yellow      Corn
Green   Broccoli
Purple  Eggplant
